'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { init, AirstackProvider } from "@airstack/airstack-react";
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'SuperFluid Airstack App',
//   description: 'Generated by socialrankcapitalFarcaster using Superfluid Stream ',
// }
const apiKey = process.env.NEXT_PUBLIC_AIRSTACK_API_KEY || " "


if (!apiKey) {
  throw new Error("No API key provided");
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AirstackProvider apiKey={apiKey}>
    <html lang="en" >
      <body className={inter.className}>
        {children}
        </body>
    </html>
    </AirstackProvider>
  )
}
